import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-12 md:p-24">
          <div className="z-10 w-full max-w-5xl items-center justify-between text-sm lg:flex flex-col">
            <Providers>{children}</Providers>
          </div>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
